# Generated by Django 5.2.1 on 2025-05-21 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('FRIEND', 'Friend')], default='FRIEND')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_first_user', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_second_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user1', 'user2', 'relationship_type'), name='unique_relationship'), models.CheckConstraint(condition=models.Q(('user1', models.F('user2')), _negated=True), name='not_same_user')],
            },
        ),
    ]
